GET http://localhost:1727/api/codes
Authorization: Bearer {{$dotenv TOKEN}}

###

GET http://localhost:1727/api/codes?page=1
Authorization: Bearer {{$dotenv TOKEN}}

###

GET http://localhost:1727/api/codes?search=official
Authorization: Bearer {{$dotenv TOKEN}}
