# 
#   Creates a new short code.
#   Created On 02 February 2022
# 

POST http://localhost:1727/api/codes
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "code": "twitter",
    "tags": "Official;Social",
    "links": [
        {
            "url": "https://twitter.com/vsnthdev"
        }
    ]
}
