# 
#   Updates an existing short code.
#   Created On 02 February 2022
# 

POST http://localhost:1727/api/codes?force=true
Content-Type: application/json
Authorization: Bearer {{$dotenv TOKEN}}

{
    "code": "twitter",
    "links": [
        {
            "url": "https://github.com/vsnthdev"
        }
    ]
}
